//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistrictPlayGroundManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public Nullable<int> Bookingid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> concession { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
