//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistrictPlayGroundManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int id { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> Teamid { get; set; }
        public Nullable<int> Groundid { get; set; }
        public string Date { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Ground Ground { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
