//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistrictPlayGroundManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int id { get; set; }
        public Nullable<int> Groundid { get; set; }
        public Nullable<int> Userid { get; set; }
        public string Details { get; set; }
    
        public virtual Ground Ground { get; set; }
        public virtual User User { get; set; }
    }
}
